{
  "annualrevenue": "5.0E7",
  "azure_revenue": null,
  "cmp_aws_revenue": null,
  "cmp_aws_services": null,
  "cmp_g_suite": "false",
  "cmp_amazon_web_services": null,
  "cmp_gcp_revenue": null,
  "cmp_google_cloud": "false",
  "cmp_link___company": null,
  "cmp_microsoft_azure": "false",
  "cmp_office_365": "false",
  "domain": "10xbanking.com",
  "consolidation_date": null,
  "country": "United Kingdom",
  "doit_parent_sales_region__c": "UK",
  "flexsave_gcp_marketplace": "False",
  "hubspot_state_region__c": "Greater London",
  "industry": null,
  "lifecycle_stage__c": "Tele Accepted Lead",
  "marketing_right": null,
  "name": "10xBanking",
  "numberofemployees": "5000",
  "o365_revenue": null,
  "phone": "+44 20 3912 0186",
  "sfdc_account_id": "0018c00002Io7gJAAR",
  "sfdc_became_a_former_customer": null,
  "sfdc_segment": null,
  "sfdc_sub_region": null,
  "state": "Greater London",
  "sub_industry__c": null,
  "website": "10xbanking.com"
}