{
  "annualrevenue": null,
  "azure_revenue": "0.0",
  "cmp_aws_revenue": "0.0",
  "cmp_aws_services": null,
  "cmp_g_suite": "false",
  "cmp_amazon_web_services": null,
  "cmp_gcp_revenue": "0.0",
  "cmp_google_cloud": "false",
  "cmp_link___company": null,
  "cmp_microsoft_azure": "false",
  "cmp_office_365": "false",
  "domain": "totalKT.com",
  "consolidation_date": null,
  "country": null,
  "doit_parent_sales_region__c": null,
  "flexsave_gcp_marketplace": "False",
  "hubspot_state_region__c": null,
  "industry": null,
  "lifecycle_stage__c": null,
  "marketing_right": null,
  "name": "total KT",
  "numberofemployees": null,
  "o365_revenue": "0.0",
  "phone": null,
  "sfdc_account_id": "0017600000ZJBgjAAH",
  "sfdc_became_a_former_customer": null,
  "sfdc_segment": null,
  "sfdc_sub_region": null,
  "state": null,
  "sub_industry__c": null,
  "website": "totalkt.com"
}